### ISSUE TITLE
Adjust solver names so they are automatically parsed

### ISSUE THREAD

**Issue by fridex** [thoth-station/solver#144]
Currently, solver names are named something like "solver-f28". This makes it harder to map to actual environments that are named like "fedora:28" (based on container images). It would be nice to consolidate on solver naming so that we can automatically create environment names in the graph database.

The proposed naming schema is:

``solver-<container-image-name>-<tag>``

So the solver-f28 becomes ``solver-fedora-28``.

**Comment by fridex** [comment]
CC @goern

**Comment by goern** [comment]
I think `container-image-name` should be NAME as in `/etc/os-release` and `tag` should be VERSION_ID as in `/etc/os-release`.

And should we add ECOSYSTEM_VERSION as `python tag` in https://www.python.org/dev/peps/pep-0425/ ?

so it would be `solver-fedora-28-py37` or `solver-rhel-7.5-py36

**Comment by fridex** [comment]
We should document this, The linked PR #169 is starting to use this naming convention.

**Comment by fridex** [comment]
Merged so closing this.
