### ISSUE TITLE
[SPIKE] Max retries exceeded with url: pypi.org/pypi/mypy-boto3-route53-recovery-cluster/json

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/solver#5200]
**Describe the bug**

From https://sentry.io/organizations/thoth-station/issues/3514246101/?alert_rule_id=529086&alert_timestamp=1660885107902&alert_type=email&environment=ocp4-stage&project=1298083&referrer=alert_email

Environment: stage

It seems like solver exceeded the rate limit of the PyPI API and was not able to retrieve https://pypi.org/pypi/mypy-boto3-route53-recovery-cluster/json from the index.

We should make sure we do not overload PyPI's API and do not get rate limited.

**Acceptance Criteria**

- [x] Ensure `mypy-boto3-route53-recovery-cluster` is on pypi.
- [ ] Execute the package for solving via management-api.
- [ ] Check if the package is available as advise result. 
- [ ] Identify the scenario where wrong package can break solvers.

**Comment by KPostOffice** [comment]
It seems PyPI has no rate limit. See: https://warehouse.pypa.io/api-reference/index.html#rate-limiting

**Comment by codificat** [comment]
According to the sentry page, it was a (temporary) DNS resolution issue:

```
host='pypi.org' [...] Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
```

Would that not be automatically re-attempted?

**Comment by codificat** [comment]
FWIW, this package has all its versions in the db:

```
$ http 'https://khemenu.thoth-station.ninja/api/v1/python/package/versions?name=mypy-boto3-route53-recovery-cluster' | jq -r '.versions[].package_version' | tail
1.21.31.post1
1.21.34
1.21.9
1.22.0
1.22.0.post1
1.22.8
1.23.0
1.23.0.post1
1.24.0
1.24.36.post1
```

**Comment by harshad16** [comment]
As noted above the data has been synced.
seems like the DNS issue caused this.
the underlying urllib retries 3 times before raising exception 
seems like as we cant set rate limit for pypi,we have rest as needed.
closing this issue.
