### ISSUE TITLE
Some package indexes have forbidden access

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/solver#5221]
## Bug description

When running solvers, the following error occurs when trying to reach some dependency indexes:

```
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://download.pytorch.org/whl/cpu/six
```

The indexes concerned are `https://download.pytorch.org/whl/cu111/` and `https://download.pytorch.org/whl/cpu/`.

### Steps to Reproduce

Run a solver for a package in the management API and observe the solver logs.
In the case of the error above, the solver scheduled was `fedora-35-py310` and the package `copr` with version specifier `"*"`.

### Expected behavior

All indexes used by solvers are accessible.

**Comment by harshad16** [comment]
we are catching these errors and implemented exception handling via https://github.com/thoth-station/python/pull/481
in solvers.
This would be caught and reflected in logging.
closing this issue.
please feel free to open it again if needed.
thanks.
