### ISSUE TITLE
Solvers fail in stage because of OOM error

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/solver#5246]
**Describe the bug**
See the last solver runs on `thoth-middletier-stage`.
Some of the solver pods fail with a similar error message:
```
pods "solver-fedora-34-py39-221114015238-660cd0639dd319e5-3878457bjjx" is forbidden: exceeded quota: thoth-middletier-stage-quota, requested: limits.memory=1768Mi, used: limits.memory=98000Mi, limited: limits.memory=96Gi
```

**To Reproduce**
Go to stage cluster and look at main container logs

**Expected behavior**
Pods have enough memory resources to finish executing.

**Comment by harshad16** [comment]
similar to: https://github.com/thoth-station/thoth-application/issues/2690

**Comment by mayaCostantini** [comment]
Closing as duplicate of https://github.com/thoth-station/thoth-application/issues/2690
