### ISSUE TITLE
solver required docker socket?

### ISSUE THREAD

**Issue by goern** [thoth-station/solver#526]
**Describe the bug**
`MountVolume.SetUp failed for volume "docker-sock" : hostPath type check failed: /var/run/docker.sock is not a socket file`

**To Reproduce**
use OCP 4.3 with crio

**Comment by goern** [comment]
This might also be an Argo RBAC problem in my test environment...

**Comment by fridex** [comment]
Solver does not need the docker socket.

> This might also be an Argo RBAC problem in my test environment...

Check `containerRuntimeExecutor` in the Argo's configmap. It defaults to docker in our ansible role - `k8sapi` should work.
