### ISSUE TITLE
Solver is able to send Kafka message for Solved Packages [8pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/solver#579]
Modify solver workflow to produce kafka messages to assess new package have been solved using workflow task to produce the message through thoth-messaging CLI and [NOKR] [5pt]

**Pre-requisites**

- [x] Having CLI in thoth-messaging to produce messages (https://github.com/thoth-station/messaging/issues/167)

**Acceptance Criteria**

- [x] Create SolvedPackage message in thoth-messaging (https://github.com/thoth-station/messaging/pull/178)
- [x] Create workflow-helper task to parse solver inputs and store Kafka inputs. (https://github.com/thoth-station/workflow-helpers/pull/25)
- [x] New release of workflow-helpers
- [x] Create new workflow task that produce SolvedPackage message using thoth-messaging CLI (https://github.com/thoth-station/thoth-application/pull/151)
- [x] Add new workflow tasks to solver (https://github.com/thoth-station/thoth-application/pull/152)

References:
- https://trello.com/c/sm79pxh8

**Comment by fridex** [comment]
I think the [thoth-station/messaging](https://github.com/thoth-station/messaging) module can be turned into a CLI tool that can produce messages based on parameters/environment variables. This way we get a new component that can be used in workflows to produce messages. As we did similarly for graph-sync.

CC @KPostOffice

**Comment by KPostOffice** [comment]
I can do this, but what's the benefit of this over sending the message using the library at the end of whatever script is being used?

**Comment by fridex** [comment]
> I can do this, but what's the benefit of this over sending the message using the library at the end of whatever script is being used?

Decoupling the logic - the system is made of multiple components, each doing its job properly. Putting such logic across all the components can easily cause maintenance issues and dependency hell.

**Comment by KPostOffice** [comment]
Do we want to have this CLI have the ability of sending any number of messages?

**Comment by fridex** [comment]
> Do we want to have this CLI have the ability of sending any number of messages? or just one?

I think just one would work well. Otherwise we can create multiple steps in the Argo workflow.
