### ISSUE TITLE
add and enable Fedora 33 Python 3.{9|9} solver in test and stage

### ISSUE THREAD

**Issue by goern** [thoth-station/solver#634]

**Comment by fridex** [comment]
/remove-lifecycle stale

We should add solvers and corresponding Thoth s2i for f33 following: https://github.com/thoth-station/thoth-application/blob/master/thoth_s2i_procedure.md

We currently support f32

**Comment by goern** [comment]
... and F34

/kind feature
/label hacktoberfest
/label "good first issue"
/priority important-soon

**Comment by goern** [comment]
superseded by #663 
/close
