### ISSUE TITLE
update solver set, fc33|34|rhel8|py38|py39

### ISSUE THREAD

**Issue by fridex** [thoth-station/solver#663]
**Is your feature request related to a problem? Please describe.**

Fedora 33/34 is already available. We should provide solver and ingest data. Let's wait for https://github.com/thoth-station/solver/pull/662

**Describe the solution you'd like**

- [x] provide s2i-thoth base container image
- [ ] provide solver-fedora-33-py{38|39} derived from the s2i-thoth container image
- [ ] provide solver-fedora-34-py38 derived from the s2i-thoth container image
- [x] provide solver-fedora-34-py39 derived from the s2i-thoth container image
- [ ] provide solver-fedora-34-py310
- [ ] provide solver-rhel-8-py39
- [ ] install solver and ingest data

**References**

* https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html/8.4_release_notes/New-features#enhancement_dynamic-programming-languages-web-and-database-servers
* https://fedoramagazine.org/python-3-10-beta-in-fedora-linux/

**Comment by fridex** [comment]
/remove-lifecycle stale

As discussed on the call, we can also have fedora-34 later on. CC @harshad16

**Comment by goern** [comment]
and RHEL8.4 also introduced py39
/remove-priority important-longterm
/priority important-soon
/kind feature

**Comment by goern** [comment]
as https://catalog.redhat.com/software/containers/ubi8/python-39/6065b24eb92fbda3a4c65d8f?gti-tabs=unauthenticated is available, its time to get this included

/priority critical-urgent

**Comment by goern** [comment]
see also https://chat.google.com/room/AAAA9x27brI/5BbdFFRvPRA

**Comment by goern** [comment]
seeAlso https://chat.google.com/room/AAAAVjnVXFk/eUICAILJw4w

**Comment by goern** [comment]
/help 

can someone take rhl8-py39, or outline what needs to be done to start ingesting data for rhel8-py39

**Comment by fridex** [comment]
> /help
> 
> can someone take rhl8-py39, or outline what needs to be done to start ingesting data for rhel8-py39

I think we should have built container images ready. We have a planned sync with @harshad16 on this today.

**Comment by fridex** [comment]
This one is blocked by https://github.com/thoth-station/thoth-application/issues/1895. Not sure of the current state of solver-rhel-8-py38 in stage environment as package-releases job fails. If we are finishing solver-rhel-8-py38, then we can proceed with a new solver.
