### ISSUE TITLE
add signature status to each solved package

### ISSUE THREAD

**Issue by goern** [thoth-station/solver#742]
**Is your feature request related to a problem? Please describe.**
As a Consumer of solver documents, I want to get information on the signature of each package solved, so that I can aggregate these in a metrics dashboard or so that they can be reused in an advise.

**Describe the solution you'd like**
tbd

**Describe alternatives you've considered**
tbd

**Additional context**
tbd

**Comment by pacospace** [comment]
is it related to Sig store?

**Comment by goern** [comment]
ja
